<a href="https://colab.research.google.com/github/Leo-Mtz/mineria-de-datos/blob/main/ExamenFinalMineria_177192.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
#Examen final Mineria de datos
#Leo Martinez-177192

In [58]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Problema de probabilidad condicional
En una fábrica se producen piezas mediante dos máquinas, A y B.

La máquina A produce el 60% del total de las piezas.
La máquina B produce el 40% restante.
Sin embargo, no son igual de precisas:

La máquina A produce 2% de piezas defectuosas.
La máquina B produce 5% de piezas defectuosas.
Un inspector toma una pieza al azar del inventario general y encuentra que la pieza está defectuosa.

Pregunta:

¿Cuál es la probabilidad de que la pieza haya sido fabricada por la máquina B?

In [59]:
import numpy as np
import pandas as pd

import numpy as np

In [60]:
p_maquina_a = 0.60
p_maquina_b = 0.40

p_defectuosas_a = 0.02
p_defectuosas_b = 0.05

# 1. P(D) = P(D|A)*P(A) + P(D|B)*P(B)
p_D = (p_defectuosas_a * p_maquina_a) + (p_defectuosas_b * p_maquina_b)

# 2. P(D ∩ B) - Probabilidad de que la pieza sea defectuosa Y de la M!quina B
p_D_inter_B = p_defectuosas_b * p_maquina_b

# --- Aplicaci!n de la F!rmula de Probabilidad Condicional ---
# P(B|D) = P(D ∩ B) / P(D)
p_B_dado_D = p_D_inter_B / p_D

# --- Mostrar el Resultado ---
print(f"Producci!n M!quina A: {p_maquina_a * 100:.0f}%")
print(f"Producci!n M!quina B: {p_maquina_b * 100:.0f}%")
print(f"Tasa de defectos M!quina A: {p_defectuosas_a * 100:.0f}%")
print(f"Tasa de defectos M!quina B: {p_defectuosas_b * 100:.0f}%")
print(f"\nP(D) probabilidad total de pieza defectuosa: {p_D:.4f}")
print(f"P(D ∩ B) probabilidad de defectuosa Y de M!quina B: {p_D_inter_B:.4f}")
print(f"La probabilidad condicional P(B|D) es: {p_B_dado_D:.3f} ({p_B_dado_D * 100:.1f}%)")

Producci!n M!quina A: 60%
Producci!n M!quina B: 40%
Tasa de defectos M!quina A: 2%
Tasa de defectos M!quina B: 5%

P(D) probabilidad total de pieza defectuosa: 0.0320
P(D ∩ B) probabilidad de defectuosa Y de M!quina B: 0.0200
La probabilidad condicional P(B|D) es: 0.625 (62.5%)

Calcula la probabilidad condicional de aprobar si se tomó el curso

In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


aprobo= {"Si":45, "No":5, "total":45+5}
reprobo= {"Si":20, "No":30, "total":20+30}
total= aprobo["total"] + reprobo["total"]

In [62]:
# a) P(A|B)
P_A_given_B_exact = aprobo["Si"] / aprobo["total"]
print("Probabilidad de aprobar el curso dado que se tomo:", P_A_given_B_exact)

Probabilidad de aprobar el curso dado que se tomo: 0.9

Problema practico de RMSE

In [63]:


import numpy as np
import pandas as pd

import numpy as np

predichos = np.array([2, 8, 4, 9])
observados = np.array([3, 7, 5, 10])

errores = observados - predichos
errores_cuadrados = errores**2

suma_errores_cuadrados = np.sum(errores_cuadrados)
mse = suma_errores_cuadrados / len(errores)
rmse = np.sqrt(mse)

print(rmse)

1.0

Pregunta 16

In [64]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/ventas.csv", parse_dates= ["fecha"])

df = df.set_index("fecha")

print(df.head(3))

print(df.info())

           producto  unidades  precio_unitario
fecha
2025-01-03        A        10            120.5
2025-01-05        B         7             98.0
2025-01-06        A         3            120.5
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4 entries, 2025-01-03 to 2025-01-10
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   producto         4 non-null      object
 1   unidades         4 non-null      int64
 2   precio_unitario  4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 128.0+ bytes
None

Pregunta 17-Items

In [65]:
#Items
import pandas as pd
dfi = pd.read_csv('/content/drive/MyDrive/items.csv')
display(dfi.head())

  categoria item  precio  cantidad
0         A    x     100         2
1         A    y     250         1
2         B    z      80         5
3         B    w     120         3
4         A    k     200         2

In [66]:

# Columna importe
dfi['importe'] = dfi.eval('precio * cantidad')


display(dfi.head())

  categoria item  precio  cantidad  importe
0         A    x     100         2      200
1         A    y     250         1      250
2         B    z      80         5      400
3         B    w     120         3      360
4         A    k     200         2      400

In [67]:

# Filtro para Categoria A
dfa = dfi.query("categoria == 'A'")


display(dfa)

  categoria item  precio  cantidad  importe
0         A    x     100         2      200
1         A    y     250         1      250
4         A    k     200         2      400

In [68]:

# Calcular el promedio de importe por categoria
promedio_categoria = dfi.groupby('categoria')['importe'].mean()

display(promedio_categoria)

categoria
A    283.333333
B    380.000000
Name: importe, dtype: float64

Pregunta 19 - Clientes y Ordenes

In [69]:
#Ordenes
import pandas as pd
dfo = pd.read_csv('/content/drive/MyDrive/ordenes.csv')
display(dfo.head())

   orden_id  cliente_id  monto
0       101           1    300
1       102           1    150
2       103           3    200
3       104           5    400

In [70]:
#Clientes
import pandas as pd
dfc = pd.read_csv('/content/drive/MyDrive/clientes.csv')
display(dfc.head())

   cliente_id  nombre  segmento
0           1     Ana   Premium
1           2    Luis  Standard
2           3  Camila  Standard
3           4    Jose   Premium

In [71]:
# Left merge de dfc con dfo
df_merged = dfc.merge(dfo, on='cliente_id', how='left')

#resultado del merge
display(df_merged)

   cliente_id  nombre  segmento  orden_id  monto
0           1     Ana   Premium     101.0  300.0
1           1     Ana   Premium     102.0  150.0
2           2    Luis  Standard       NaN    NaN
3           3  Camila  Standard     103.0  200.0
4           4    Jose   Premium       NaN    NaN

In [72]:
# Monto total por cliente
monto_por_cliente = df_merged.groupby(['cliente_id', 'nombre'])['monto'].sum().fillna(0).reset_index()


display(monto_por_cliente)

   cliente_id  nombre  monto
0           1     Ana  450.0
1           2    Luis    0.0
2           3  Camila  200.0
3           4    Jose    0.0

Pregunta 21- Sensores

In [73]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/sensores.csv', usecols=['ts', 'temperatura', 'humedad'])
display(df.head())

# Convertir la columna ts a datetime con formato mixto
df['ts'] = pd.to_datetime(df['ts'], format='mixed', errors='coerce')

print(df.dtypes)
display(df.head())

                    ts  temperatura  humedad
0     2025-02-01 10:00         23.5     45.2
1     2025/02/01 10:05          NaN     46.0
2     01-02-2025 10:10         22.1      NaN
3  2025-02-01T10:15:00          NaN     47.3

ts             datetime64[ns]
temperatura           float64
humedad               float64
dtype: object

                   ts  temperatura  humedad
0 2025-02-01 10:00:00         23.5     45.2
1 2025-02-01 10:05:00          NaN     46.0
2 2025-01-02 10:10:00         22.1      NaN
3 2025-02-01 10:15:00          NaN     47.3

In [74]:
# Reemplazar valores faltantes en temperatura con la mediana
df['temperatura'] = df['temperatura'].fillna(df['temperatura'].median())

# Reemplazar valores faltantes en humedad con la media
df['humedad'] = df['humedad'].fillna(df['humedad'].mean())

print(df.isnull().sum())
display(df.head())

ts             0
temperatura    0
humedad        0
dtype: int64

                   ts  temperatura    humedad
0 2025-02-01 10:00:00         23.5  45.200000
1 2025-02-01 10:05:00         22.8  46.000000
2 2025-01-02 10:10:00         22.1  46.166667
3 2025-02-01 10:15:00         22.8  47.300000

In [75]:
# ¿Cuántos NaT quedaron en ts?
nat_count = df['ts'].isna().sum()
print(f'Cantidad de NaT en la columna ts: {nat_count}')

Cantidad de NaT en la columna ts: 0

In [76]:
# Valor final de la mediana de temperatura tras imputación (redondeado a 1 decimal)
mediana_final = df['temperatura'].median()
print(f'La mediana final de temperatura es: {round(mediana_final, 1)}')

La mediana final de temperatura es: 22.8

In [77]:
# Valor final de la media de humedad tras imputación (redondeado a 3 decimales)
media_final_hum = df['humedad'].mean()
print(f'La media final de humedad es: {round(media_final_hum, 3)}')

La media final de humedad es: 46.167

#Agua y Cafe

In [78]:
import pandas as pd
import numpy as np


# Establece una semilla para reproducibilidad
np.random.seed(42)


# 1. Crea una lista de matrículas de estudiantes
student_ids = [f'{i:06d}' for i in range(172120, 172120 + 20)]


# 2. Asigna 10 estudiantes al grupo 'Café' y 10 al grupo 'Agua'
groups = ['Café'] * 10 + ['Agua'] * 10
np.random.shuffle(groups)


# 3. Simula calificacionen de examenes para el grupo café
# Mean=70, Std=5, asegurate de que los valores estén entre (50-100)
coffee_scores = np.random.normal(loc=70, scale=5, size=10).round(0)
coffee_scores = np.clip(coffee_scores, 50, 100).astype(int)


# 4. Simula calificaciones de examen para el grupo de 'Agua'
# Mean=75, Std=5, asegurate de que los valores estén entre (50-100)
water_scores = np.random.normal(loc=75, scale=5, size=10).round(0)
water_scores = np.clip(water_scores, 50, 100).astype(int)


# Combina los valores basado en el grupo
exam_scores = []
coffee_idx = 0
water_idx = 0
for group in groups:
    if group == 'Café':
        exam_scores.append(coffee_scores[coffee_idx])
        coffee_idx += 1
    else:
        exam_scores.append(water_scores[water_idx])
        water_idx += 1


# 5. Combina en un DataFrame de Pandas
df_students = pd.DataFrame({
    'Matrícula': student_ids,
    'Grupo': groups,
    'Calificaciones': exam_scores
})


print("Datos simulados:")
print(df_students.head())

Datos simulados:
  Matrícula Grupo  Calificaciones
0    172120  Café              77
1    172121  Agua              77
2    172122  Agua              79
3    172123  Café              78
4    172124  Café              58

In [79]:
# Calcula la media de calificaciones para el grupo 'Agua'
calificaciones_agua = df_students[df_students['Grupo'] == 'Agua']['Calificaciones']
media_agua = calificaciones_agua.mean()

print(f"\nMedia de calificaciones del grupo 'Agua': {media_agua:.2f}")

Media de calificaciones del grupo 'Agua': 74.90

Media Café: 70.60
Media Agua: 74.90

Mediana Café: 71.00
Mediana Agua: 75.00